
[package]
name = "RustPython"
version = "0.0.1"
authors = [ "Shing Lyu", "Windel Bouwman" ]
build = "build.rs"

[build-dependencies]
lalrpop="0.20.0"

[dependencies]
clap="2.20.0"
lalrpop-util="0.20.0"
regex="0.2.2"
log="0.4.1"
env_logger="0.5.10"

